### ISSUE TITLE
User is returned values after clicking a button for LIQUOR.

### ISSUE THREAD

**Issue by darrindevs** [darrindevs/netflix-and-chilled-cocktails#11]
User can click ONE of the following buttons:

1. Random   / id= lr-btn
2. Liquor 1  / id= l1-btn
3. Liquor 2 / id= l2-btn
4. Liquor 3 / id= l3-btn
5. Liquor 4  / id= l4-btn
6. Liquor 5  / id= l5-btn

----------
- Each button is hard coded to a specific API query
- The values received back are: Name of selected liquor, name of cocktail, ingredients list (what else?
- An image is received
- All values are inserted dynamically into a list

**Comment by erickmeline** [comment]
P.R. sent: https://github.com/darrindevs/netflix-and-chilled-cocktails/pull/15
js is in place for fetching drink data.
event listeners can be added at any time to send an ingredient (i.e. gin, vodka) or nothing, which will kick off a request to fetch an individual drink object, parsed and ready for inclusion in the view (frontend).
