### ISSUE TITLE
User can click a button to filter preference for LIQUOR.

### ISSUE THREAD

**Issue by darrindevs** [darrindevs/netflix-and-chilled-cocktails#12]
User can click ONE of the following buttons:

1.  Random   / id= lr-btn
2. Liquor 1  / id= l1-btn
3. Liquor 2 / id= l2-btn
4. Liquor 3 / id= l3-btn
5. Liquor 4  / id= l4-btn
6. Liquor 5  / id= l5-btn

----------
- Each button is hard coded to a specific API query

**Comment by Jsbaxter560** [comment]
buttons for liquor types have been generated for user to choose from
