### ISSUE TITLE
FRONT END: User can click a button to filter preference for MOVIES.

### ISSUE THREAD

**Issue by darrindevs** [darrindevs/netflix-and-chilled-cocktails#9]
User can click ONE of the following buttons:

1.  Random   / id=random-btn
2. Genre 1  / id= g1-btn
3. Genre 2 / id= g2-btn
4. Genre 3 / id= g3-btn
5. Genre 4  / id= g4-btn
6. Genre 5 / id= g5-btn
7. Actor 1 / id= a1-btn
8. Actor 2  / id= a2-btn
9. Actor 3 / id= a3-btn
10. Actor 4 / id= a4-btn
11. Actor 5 / id= a6-btn
----------
- Each button is hard coded to a specific API query

**Comment by Jsbaxter560** [comment]
a selection of genre buttons have been generated for user to select from
